[[section-deployment-linux]]

== Linux Deployment

This is description of services,dependencies and steps  to run XS2ASandbox on any linux system.

.Table of services and dependencies:

[%autowidth.stretch]
|===
|Service | Dependencies | Environment variables | Ports

|xs2a-connector-examples | Java 11 | SPRING_PROFILES_ACTIVE | 8089,8189
| | |ASPSP-PROFILE_BASEURL |
| | |CMS_URL |
| | |LEDGERS_URL |
| | |CONSENT_SERVICE_BASEURL |
| | |SPRING_PROFILES_ACTIVE |
| | |skip_ssl_certificate_verification |
| | |DB_PASSWORD |
| | |DB_USER |
| | |DB_DATABASE |
| | |DB_HOST |
|xs2a-asps--profile |Java 11 | SPRING_PROFILES_ACTIVE | 48080
| | | BANK_PROFILE_PATH |
|xs2a-consent-management |Java 11 | ASPSP-PROFILE_BASEURL | 38080
| | |SPRING_DATASOURCE_URL  |
| | |SPRING_DATASOURCE_USERNAME  |
| | |SPRING_DATASOURCE_PASSWORD  |
| | |SERVER_KEY  |
| | |SPRING_LIQUIBASE_ENABLED  |
| | |SPRING_LIQUIBASE_URL  |
| | |SPRING_LIQUIBASE_DEFAULT_SCHEMA  |
| | |SPRING_LIQUIBASE_USER  |
| | |SPRING_LIQUIBASE_PASSWORD  |
| | |USED-NON-RECURRING-CONSENT-EXPIRATION.CRON.EXPRESSION  |
| | |SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA  |
| | |skip_ssl_certificate_verification  |
| xs2a-consent-management-db | Postgresql 9.5 | POSTGRESQL_ADMIN_PASSWORD | 5432
| | | POSTGRESQL_DATABASE  |
| | | POSTGRESQL_USER  |
| | | POSTGRESQL_PASSWORD |
|xs2a-online-banking | NGINX 1.15.5 |XS2A_URL| 8090,8190
| | | LEDGERS_URL  |
| | | CMS_URL  |
| | | ONLINE_BANKING_SCA_LOGINPAGE  |
| | | ONLINE_BANKING_SCA_UIREDIRECT  |
| | | MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_METHODS  |
| | | MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS  |
|ledgers | Java 8 | SPRING_PROFILES_ACTIVE | 8088,8188
| | | SPRING_JPA_SHOW_SQL  |
| | | DB_HOST  |
| | | DB_URL  |
| | | DB_DATABASE  |
| | | DB_USER  |
| | | DB_PASSWORD  |
| | | LIQUIBASE_ENABLED  |
| | | SCA_MULTILEVEL_ENABLED  |
| | | SPRING_MAIL_HOST  |
| | | SPRING_MAIL_PORT  |
| | | SPRING_MAIL_USERNAME  |
| | | SPRING_MAIL_PASSWORD  |
| | | SPRING_MAIL_PROPERTIES_MAIL_FROM  |
| | | SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH  |
| | | SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE |
|xs2a-online-banking-ui  |NGINX 1.15.5 | ONLINE_BANKING_SERVER_URL | 4400
| | | DEV_PORTAL_URL_EXT |
|xs2a-tpp-ui | NGINX 1.15.5 | LEDGERS_URL | 4205
| | | TPP_REST_SERVER_URL |
| | | CERT_GEN_URL |
| xs2a-tpp-rest-server | Java 11 | LEDGERS_URL | 8093
| | | SPRING_DATASOURCE_URL  |
| | | SPRING_DATASOURCE_USERNAME  |
| | | SPRING_DATASOURCE_PASSWORD  |
| | | SERVER_KEY  |
| | | USED-NON-RECURRING-CONSENT-EXPIRATION.CRON.EXPRESSION  |
| | | NOT-CONFIRMED-CONSENT-EXPIRATION.CRON.EXPRESSION  |
| | | NOT-CONFIRMED-PAYMENT-EXPIRATION.CRON.EXPRESSION  |
| | | CONSENT.CRON.EXPRESSION  |
| | | STOPLIST.CRON.EXPRESSION  |
| | | ENCRYPTION.CRON.EXPRESSION  |
| | | IBAN_GENERATOR_BANKCODE_NISP  |
| | | IBAN_GENERATOR_BANKCODE_RANDOM  |
| | | IBAN_GENERATOR_COUNTRYCODE  |
|developer-portal-ui | NGINX 1.15.5 | XS2A_URL | 4206
|ledgers-db |  Postgresql 9.5  | POSTGRESQL_ADMIN_PASSWORD | 5432
| | | POSTGRESQL_DATABASE  |
| | | POSTGRESQL_USER  |
| | | POSTGRESQL_PASSWORD |
|certificate-generator | Java 11 | - | 8092
| smtp server | any mail server to accept and send smtp messages | |
|===

== 1. Prerequisites

The applications need the prerequisites described below. You need to install prerequisites via your linux distributions package manager.
Select your linux distribution in the provided manual links.

=== 1.1 PostgreSQL

Manual to install PostgreSQL on linux server:
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-centos-7

=== 1.2 Java 11

Manual to install Java 11 on linux server:
https://www.digitalocean.com/community/tutorials/how-to-install-java-on-centos-and-fedora

=== 1.3 NGINX

Manual to install NGINX on linux server:
https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-centos-7

=== 1.4 Mail Server

Additionally you need a working mail server.
This manual will not cover its installation.

== 2. Configuration

=== 2.1 PostgreSQL Databases

The application needs two databases. One for consent-management-system and one for ledgers.

Therefore we need to create these databases and two corresponding users.

```sh
$ sudo -u postgres psql
```

==== 2.1.1 Create and configure ledgers-db:

* create database:
```sh
$ postgres=# CREATE DATABASE ledgers;
```

* create user and password:
```sh
$ postgres=# CREATE USER ledgersdb WITH ENCRYPTED PASSWORD 'password-to-change';
```

* grant accesses:
```sh
$ postgres=# GRANT ALL PRIVILEGES ON DATABASE ledgers TO ledgersdb;
```

==== 2.1.2 Create and configure xs2a-consent-management-system-db:

* create database:
```sh
$ postgres=# CREATE DATABASE cms;
```

* create user and password:
```sh
$ postgres=# CREATE USER cmsdb WITH ENCRYPTED PASSWORD 'password-to-change';
```

* grant accesses:
```sh
$ postgres=# GRANT ALL PRIVILEGES ON DATABASE cms TO cmsdb;
```

* create cms schema:
```sh
$ postgres=# CREATE SCHEMA consent AUTHORIZATION cmsdb;
```

=== 2.2 Java Backend
==== 2.2.1 Java applications

* create directory for application binaries

```sh
$ mkdir /opt/sandbox
```

* copy the binaries:

```sh
$ cp *.jar /opt/sandbox/
```

* make the binaries executable:

```sh
$ chmod +x /opt/sandbox/*.jar
```

* run the binaries (through a startup script on server boot):

```sh
$ $JAVA_HOME/bin/java $JAVA_OPTS_ASPSP_PROFILE -jar /opt/sandbox/aspsp-profile.jar
$ $JAVA_HOME/bin/java $JAVA_OPTS_CMS -jar /opt/sandbox/consent-management.jar
$ $JAVA_HOME/bin/java $JAVA_OPTS_GATEWAY -jar /opt/sandbox/gateway-app.jar
$ $JAVA_HOME/bin/java $JAVA_OPTS_LEDGERS -jar /opt/sandbox/ledgers-app.jar
$ $JAVA_HOME/bin/java $JAVA_OPTS_OBA -jar /opt/sandbox/xs2a-online-banking.jar
$ $JAVA_HOME/bin/java $JAVA_OPTS_TPP -jar /opt/sandbox/tpp-rest-server.jar
$ $JAVA_HOME/bin/java -jar /opt/sandbox/certificate-generator.jar
```
NOTE: Please, note, that you have to change $JAVA_OPTS_* placeholder to the options you want to specify for every jar.
The table of options and possible configurations you can find below:


[%autowidth.stretch]
|===
| Placeholder | Service | Option | Possible configurations | Additional information
| $JAVA_OPTS_ASPSP_PROFILE | Aspsp profile | SPRING_PROFILES_ACTIVE | debug_mode | debug_mode option allows you to change Aspsp-profile options via REST API. Should be used only for testing and not in production.
| | | BANK_PROFILE_PATH | /data/bank_profile_yml (example) | Mandatory path to your profile settings in _yml file
| $JAVA_OPTS_CMS | Consent management system | ASPSP_PROFILE_BASEURL | http://demo-dynamicsandbox-aspspprofile:8080/api/v1 (example) | Mandatory URL to your Aspsp-profile application.
| | | SPRING_DATASOURCE_URL | jdbc:postgresql://localhost/cms | URL to consent_management_database
| | | SPRING_DATASOURCE_USERNAME | cmsdb | The name of the user you created when creating consent-management-system-database.
| | | SPRING_DATASOURCE_PASSWORD | password-to-change |
| | | SERVER_KEY | secret-to-change |
| | | SPRING_LIQUIBASE_ENABLED | true |
| | | SPRING_LIQUIBASE_URL | jdbc:postgresql://localhost/cms?currentSchema=consent |
| | | SPRING_LIQUIBASE_DEFAULT_SCHEMA | consent | Schema created for consent-management-database
| | | SPRING_LIQUIBASE_USER | cmsdb | The same as for SPRING_DATASOURCE_USERNAME
| | | SPRING_LIQUIBASE_PASSWORD | password_to_change | The same as for SPRING_DATASOURCE_PASSWORD
| | | USED_NON_RECURRING_CONSENT_EXPIRATION_CRON_EXPRESSION | 0 0 * * * * |
| | | SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA | consent |
| | | skip_ssl_certificate_verification | true, false | Value used in XS2A_Sandbox is true
| $JAVA_OPTS_GATEWAY | XS2A Connector examples | SPRING_PROFILES_ACTIVE | postgres,mock-qwac | mock-qwac is used only for testing, this profile mocks TPP QWAC certificate for every request. This profile should not be used for production
| | | ASPSP_PROFILE_BASEURL | http://localhost:8080/api/v1 (example) | Mandatory URL to your Aspsp-profile application.
| | | CMS_URL | http://localhost:8080 (example) | Mandatory consent-management-system URL
| | | LEDGERS_URL | http://localhost:8088 (example)| Mandatory Ledgers URL
| | | CONSENT_SERVICE_BASEURL | http://localhost:8080/api/v1 (example) | Base consent-management URL for calls to endpoints (CMS_URL + "api/v1")
| | | skip_ssl_certificate_verification | true, false | Value used in XS2A Sandbox is true
| | | DB_PASSWORD | password-to-change |
| | | DB_USER | cmsdb |
| | | DB_DATABASE | cms |
| | | DB_HOST | localhost |
| $JAVA_OPTS_LEDGERS | Ledgers | SPRING_PROFILES_ACTIVE | postgres,sandbox | Profile "sandbox" used only for test purposes to produce static TAN number (123456). Should not be used for production.
| | | DB_HOST | localhost |
| | | DB_DATABASE |ledgers |
| | | DB_USER | ledgersdb |
| | | DB_PASSWORD | password-to-change |
| | | SCA_MULTILEVEL_ENABLED | false, true | Enables or disables Multilevel SCA functionality in Ledgers.
| | | APPLICATION_SECURITY_ENCRYPTIONALGORITHM | PBEWITHSHA1ANDDESEDE | Given configuration should be used.
| | | APPLICATION_SECURITY_MASTERPASSWORD | secret2-to-change |
| | | spring_mail_host | smtp-gmail.com (example) | SMTP Server configurations. Should be configured in accordance with existing SMTP server.
| | | spring_mail_port | 587 |
| | | spring_mail_username | username |
| | | spring_mail_password | password |
| | | spring_mail_properties_mail_smtp_starttls_enable | true |
| | | spring_mail_properties_mail_smtp_auth | true |
| | | spring_mail_properties_mail_smtp_connectiontimeout | 5000 |
| | | spring_mail_properties_mail_smtp_timeout | 5000 |
| | | spring_mail_properties_mail_smtp_writetimeout | 5000 |
| $JAVA_OPTS_OBA | Online banking | XS2A_URL | http://localhost:8089 | Mandatory URL to XS2A
| | | LEDGERS_URL | http://localhost:8088 |
| | | CMS_URL | http://localhost:8080 |
| | | ONLINE_BANKING_SCA_LOGINPAGE | https://demo-dynamicsandbox-onlinebankingui-cloud-adorsys.de/ (example) | Online-banking page, to which user would be redirected in Redirect approach
| | | ONLINE_BANKING_SCA_UIREDIRECT | true, false | XS2A Sandbox uses "true" as a value in this configuration
| | | MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_METHODS | GET,POST,PUT,DELETE,OPTIONS,PATCH | CORS settings
| | | MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS | https://demo-dynamicsandbox-onlinebankingui-cloud-adorsys.de | CORS settings
| $JAVA_OPTS_TPP | TPP REST server | LEDGERS_URL | http://localhost:8088 |
| | | SPRING_DATASOURCE_URL | jdbc:postgresql://localhost/cms |
| | | SPRING_DATASOURCE_USERNAME | cmsdb |
| | | SPRING_DATASOURCE_PASSWORD | password-to-change |
| | | SERVER_KEY | secret-to-change |
| | | USED_NON_RECURRING_CONSENT_EXPIRATION_CRON_EXPRESSION | 0 0 * * * * | Cron settings for consent-management-system
| | | NOT_CONFIRMED_CONSENT_EXPIRATION_CRON_EXPRESSION | 0 0 * * * * | Cron settings for consent-management-system
| | | NOT_CONFIRMED_PAYMENT_EXPIRATION_CRON_EXPRESSION | 0 0 * * * * | Cron settings for consent-management-system
| | | CONSENT_CRON_EXPRESSION | 0 0 * * * * | Cron settings for consent-management-system
| | | STOPLIST_CRON_EXPRESSION | 0 0 * * * * | Cron settings for consent-management-system
| | | ENCRYPTION_CRON_EXPRESSION | 0 0 * * * * | Cron settings for consent-management-system
| | | IBAN_GENERATOR_BANKCODE_NISP | 76070025 |
| | | IBAN_GENERATOR_BANKCODE_RANDOM | 90000001 |
| | | IBAN_GENERATOR_COUNTRYCODE | AU | Could be changed to any country code to generate ibans with desired country code
|===


NOTE: All possible mail configurations for Spring could be found here: https://www.quickprogrammingtips.com/spring-boot/how-to-send-email-from-spring-boot-applications.html

NOTE: To use for example Gmail account and SMTP server to sent emails you should configure two-factor authentication and create application password.

=== 2.3 Nginx Frontends

* tpp-ui:

```sh
$ cp tpp-ui-nginx.conf /etc/nginx/conf.d/
$ mkdir /usr/share/nginx/html/tpp-ui/
$ cp dist/tpp-ui/* /usr/share/nginx/html/tpp-ui/
```

**tpp-ui-nginx.conf file:**

```
server {
  listen 4205;

  index index.html;
  root /usr/share/nginx/html/tpp-ui/;

  access_log /var/log/nginx/tpp-ui_access.log combined;
  error_log /var/log/nginx/tpp-ui_error.log error;

  location /tpp/ {
        proxy_pass http://localhost:8093;

        proxy_set_header          Host            $host;
        proxy_set_header          X-Real-IP       $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect default;
        proxy_http_version 1.1;
  }

  location /certgen/ {
        proxy_pass http://localhost:8092/;

        proxy_set_header          Host            $host;
        proxy_set_header          X-Real-IP       $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect default;
  }

  location / {
        proxy_intercept_errors on;
        error_page 404 = /index.html;
  }

}
```

* developerportal-ui:

```sh
$ cp developerportal-ui-nginx.conf /etc/nginx/conf.d/
$ mkdir /usr/share/nginx/html/developerportal-ui/
$ cp dist/developerportal-ui/* /usr/share/nginx/html/developerportal-ui/
```

**developerportal-ui-nginx.conf file:**

```
server {
    listen 4206;

    index index.html;
    root /usr/share/nginx/html/developerportal-ui/;

    access_log /var/log/nginx/developerportal-ui_access.log combined;
    error_log /var/log/nginx/developerportal-ui_error.log error;

    location "/xs2a-proxy/" {
        proxy_pass      http://localhost:8089/;

        proxy_set_header          Host            $host;
        proxy_set_header          X-Real-IP       $remote_addr;
        proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect default;
    }

    location / {
        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }
}
```

* onlinebanking-ui:

```sh
$ cp onlinebanking-ui-nginx.conf /etc/nginx/conf.d/
$ mkdir /usr/share/nginx/html/onlinebanking-ui/
$ cp dist/onlinebanking-ui/* /usr/share/nginx/html/onlinebanking-ui/
```

**onlinebanking-ui-nginx.conf file:**

```
server {
    listen 4400;

      index index.html;
      root /usr/share/nginx/html/onlinebanking-ui/;

      access_log /var/log/nginx/onlinebanking-ui_access.log combined;
      error_log /var/log/nginx/onlinebanking-ui_error.log error;

      location /oba-proxy/ {
            proxy_pass      http://localhost:8090/;

            proxy_set_header          Host            $host;
            proxy_set_header          X-Real-IP       $remote_addr;
            proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect default;
      }

      location / {
            proxy_intercept_errors on;
            error_page 404 = /index.html;
       }
}
```

== 3. Handling SSL-connection

* Option 1:
`TPP -> (https + tls) -> GW -> (http + header) -> Sandbox`

Using an existing gateway which terminates SSL, extracts the TPP / QWAC certificate and hands it on to the sandbox application in HTTP header.

* Option 2:
`TPP -> (https + tls) -> GW -> (https + tls) -> ssl-proxy -> (http + header) -> Sandbox`

Passing HTTPS through the existing gateway and deploying our SSL-Proxy, which will then terminate SSL, extract the TPP / QWAC certificate and hand it on to the sandbox application in HTTP header.

```sh
$ cp sandbox-xs2a-server.conf sandbox-portal-server.conf /etc/nginx/conf.d/
$ mkdir /usr/share/nginx/html/ssl-proxy/
$ cp dist/tpp-ui/* /usr/share/nginx/html/tpp-ui/
```

**sandbox-portal-server.conf file: **

```
server {
  # The Sandbox HTTPS server, which proxies our requests
  listen 8443 ssl;
  server_name $PORTAL_EXTERNAL_URL;
  ssl_protocols TLSv1.1 TLSv1.2;
  # ssl certificate
  ssl_certificate /opt/app-root/etc/nginx.pem;
  ssl_certificate_key /opt/app-root/etc/nginx.key;
  location / {
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    # Fix the "It appears that your reverse proxy set up is broken" error.
    proxy_pass          $PORTAL_INTERNAL_URL;
    # web sockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_redirect      $PORTAL_INTERNAL_URL $PORTAL_EXTERNAL_URL;
  }
}
```

**sandbox-xs2a-server.conf file:**

```
server {
  # The Sandbox HTTPS server, which proxies our requests
  listen 8443 ssl;
  server_name $API_EXTERNAL_URL;
  ssl_protocols TLSv1.1 TLSv1.2;
  # ssl certificate
  ssl_certificate /opt/app-root/etc/nginx.pem;
  ssl_certificate_key /opt/app-root/etc/nginx.key;
  # client certificate
  ssl_client_certificate /opt/app-root/etc/ca.crt;
  # make verification optional, so XS2A validates the incoming certificates
  ssl_verify_client optional;
  location / {
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_set_header        tpp-qwac-certificate $ssl_client_cert;
    # Fix the "It appears that your reverse proxy set up is broken" error.
    proxy_pass          $API_INTERNAL_URL;
    # web sockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_redirect      $API_INTERNAL_URL $API_EXTERNAL_URL;
  }
}
```
NOTE: Please, note, that you have to change placeholders to the options you want to specify.
The table of options and possible configurations you can find below:

[%autowidth.stretch]
|===
| Placeholder | URL | Description
| $PORTAL_INTERNAL_URL | localhost:4400 | internal url of online-banking-ui via HTTP
| $PORTAL_EXTERNAL_URL | psd2-sandbox-portal.denizbank.com.tr (example) | url to publish online-banking-ui externally via HTTPS
| $API_INTERNAL_URL | localhost:8089 | internal url of xs2a-connector-examples via HTTP
| $API_EXTERNAL_URL | psd2-sandbox-api.denizbank.com.tr (example) | url to publish xs2a-connector-examples externally via HTTPS
|===
