[[section-design-decisions]]
== Design Decisions

Micro-service architecture::
+
Our project design features micro-service architecture making it flexible and easily scalable, yet simple and understandable.
Project consists of:

* Angular modules for the frontend (Developer Portal, Online Banking UI, TPP UI, Admin UI)
* Java based backend modules (XS2A Interface, Consent Management, ASPSP Profile, Ledgers, Online Banking,  Admin & TPP backend, XS2A Gateway, Certificate Generator)
+

Stick to a Tech-Stack Commonly Found in Banks::
We try to be conservative in our tech choice. To reduce friction we use technologies that our potential
customers know and can handle.
+
Right now we use:

* Base technologies:
- Java 11
- Spring Boot, Spring Data, Spring WebMVC
- Hibernate
- Mapstruct
- Jackson
- Maven
- Gitlab/Github
- PostgreSQL
- Liquibase
- Lombok
- Open Feign
- JWT
- Keycloak
- Angular 11
- Docker
- Postman

* Tests:
- Mockito
- AssertJ

* Other:
- PMD Checkstyle
- SonarLint

Continuous development & update::
All projects included into ModelBank are continuously developed and updated to latest BerlinGroup PSD2 Specification and
are always up to date featuring the latest releases of all components.
