/**
 * Certificate Generator
 * Certificate Generator for Testing Purposes of PSD2 Sandbox Environment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: swi@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PspRole } from './pspRole';

/**
 * Certificate Data
 */
export interface CertificateRequest {
  roles: Array<PspRole>;
  /**
   * Available in the Public Register of the appropriate National Competent Authority;
   */
  authorizationNumber: string;
  /**
   * Registered name of your corporation
   */
  organizationName: string;
  /**
   * Name of the country your corporation is registered
   */
  countryName?: string;
  /**
   * Domain of your corporation
   */
  domainComponent?: string;
  /**
   * Name of the city of your corporation headquarter
   */
  localityName?: string;
  organizationUnit?: string;
  /**
   * Name of the state/province of your corporation headquarter
   */
  stateOrProvinceName?: string;
  /**
   * Number of days the certificate is valid
   */
  validity?: number;

  /**
   * Common name of your corporation headquarter
   */
  commonName: string;
}
